version: '3'

services:
  reservations:
    build:
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    env_file:
      - "./apps/reservations/.env"
    command: pnpm run start:dev reservations
    ports:
      - '3001:3001'

  auth:
    build:
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - "./apps/auth/.env"
    command: pnpm run start:dev auth
    ports:
      - '3002:3002'

  mongo:
    image: mongo
