version: '3'

services:
  reservations:
    build:
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    env_file:
      - ".env"
    command: pnpm run start:dev reservations
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
